export enum ConfigEnum {
    JWT_SECRET = 'JWT_SECRET',
    JWT_EXPIRATION_TIME = 'JWT_EXPIRATION_TIME',
    PORT = 'PORT',
    POSTGRES_PORT = 'POSTGRES_PORT',
    POSTGRES_USER = 'POSTGRES_USER',
    POSTGRES_DB = 'POSTGRES_DB',
    POSTGRES_HOST = 'POSTGRES_HOST',
    POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
    SENDGRID_API_KEY = 'SENDGRID_API_KEY',
    EMAIL_SENDER = 'EMAIL_SENDER',
  }